### PR TITLE
Fix losing `this` of the DOM element

### LINKED ISSUE #10: problems with __oldData__ and updated deps
I originally discovered this problem in https://github.com/romseguy/redux-devtools-chart-monitor/issues/16, but also could reproduce it outside `redux-devtools-chart-monitor` (see https://github.com/romseguy/d3-state-visualizer/pull/9).

Looks like the source of the problem [in `src/charts/tree/tree.js`](https://github.com/romseguy/d3-state-visualizer/search?utf8=%E2%9C%93&q=__oldData__). I'd specifically blame [`this.__oldData__`](https://github.com/romseguy/d3-state-visualizer/blob/cb533bf79fc7fac993c80a677e4cf3aa8f9f49f7/src/charts/tree/tree.js#L253).

### PR DESCRIPTION
**Pull request by zalmoxisus**
Fix #10.

### CODE REVIEW

**Comment by romseguy** [comment]
Released as 1.3.1

**Comment by kachkaev** [comment]
Great! I can check that straight away - still have a couple of cloned repos.

**Comment by romseguy** [comment]
Released redux-devtools-chart-monitor@1.6.1

**Comment by kachkaev** [comment]
Awesome! All worked!

**Pull request merged**
